# Generated by Django 2.1.2 on 2018-10-24 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0002_auto_20181024_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoughtCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_abbreviation', models.CharField(max_length=8)),
                ('amount', models.IntegerField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading_app.Profile')),
            ],
        ),
    ]
