# Generated by Django 2.1.2 on 2018-11-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0003_boughtcurrency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='money',
            field=models.FloatField(default=100),
        ),
    ]
