# Generated by Django 2.0.4 on 2018-09-19 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_exchange', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rates_and_dates',
            new_name='Rate_and_date',
        ),
    ]
