# Generated by Django 2.0.4 on 2018-10-02 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_exchange', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate_and_date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='currency',
            name='date',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='rate',
        ),
        migrations.AddField(
            model_name='rate_and_date',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_exchange.Currency'),
        ),
    ]
