# Generated by Django 2.1.5 on 2019-04-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_exchange', '0003_auto_20181005_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
